### ISSUE TITLE
Underbrace complex subscript rendered incorrectly

### ISSUE THREAD

**Issue by Cookie04DE** [widcardw/obsidian-asciimath#20]
The following AsciiMath get's rendered by the offical site like this:
`lim_(n->oo) underbrace(1/x)_(lim_(n->-oo) 1)`
<img width="112" alt="Bildschirmfoto 2023-11-21 um 09 31 21" src="https://github.com/widcardw/obsidian-asciimath/assets/52695768/e36524e0-779f-496e-8d44-3a102289d205">
The plugin renders it like this however:
<img width="169" alt="Bildschirmfoto 2023-11-21 um 09 31 05" src="https://github.com/widcardw/obsidian-asciimath/assets/52695768/16bb14b7-ead5-4c3b-91fe-175e14aa2993">
Notice that the complex subscript of the limit expression is broken in the underbrace

**Comment by widcardw** [comment]
That is because the `lim` is not in `\displaystyle`.

To solve this problem, just simply add a `#` before the `lim`, and the whole math block should be

```
lim_(n->oo) underbrace(1/x)_(#lim_(n->-oo) 1)
```

And the `#` will be transformed into `\displaystyle`.

The official site uses KaTeX while obsidian uses Mathjax. There may be some inconsistence here.
