### ISSUE TITLE
Insert newline into asciimath block

### ISSUE THREAD

**Issue by nikp123** [widcardw/obsidian-asciimath#5]
Apologies if this question may seem dumb but is there a way (in the current version of the plugin) to insert newlines in the asciimath block.

Example:
(triple tilda)asciimath
a = b
c = d
(triple tilda)

Thanks in advance

**Comment by widcardw** [comment]
Oops, this problem is also mentioned by my friend @zmx0142857, and I am also considering whether to use several line breaks as a sign of `aligned` environment.

The current solution should be like

~~~md
```am
& a = b
            <-- a blank line here
& c = d
```
~~~

For more information, please refer to https://asciimath.widcard.win. If you are really complaining about this problem, I'll fix it in the next version of [`asciimath-parser`](https://www.npmjs.com/package/asciimath-parser).

**Comment by nikp123** [comment]
Oh thanks, that solves my problem.

So adding ampersand before the line indicates that the line is "alone" so to speak?
