### ISSUE TITLE
Add option for overriding default math block in obsidian.

### ISSUE THREAD

**Issue by kwinso** [widcardw/obsidian-asciimath#9]
I can implement and do a PR with functionality of overriding default math block `$...$ or $$...$$` for Obsidian, which can be toggled on/off. 

Such functionality is implemented in [Obsidian Typst](https://github.com/fenjalien/obsidian-typst), for example. I find it quite convinient. 
Also, I've tried to implement LaTeX compatibilty mode in [my plugin](https://github.com/kwinso/obsidian-typst-math), so a user can use both Typst and LaTeX in their vault. Basically, it just checks math block with a regex to determine if there's any word (more than 1 character) that is prefixed with a backslash. which is kind of a indication that LaTeX is used.   
Something like this:
```
\a -> no match
\frac -> match
```

Are you interested?

**Comment by widcardw** [comment]
That's a good idea. Using \`\$ and \$\` as the delimiters may be a little bit complex, and I'd like to use double backtick (e.g. \`\`abc\`\`) to wrap the formula. 

However, it's quite hard for me to both support live preview mode and reading mode with double backtick, since in live preview mode, the code wrapped by double backtick will just be recognized as a HTMLCodeElement, no more backticks.

> It's such a long time that I forgot why I cannot implement the double backtick feature... After reviewing the code, I think it's not a problem...

https://github.com/widcardw/obsidian-asciimath/blob/e7b6cae2d3b63aad6dfcd7b01bf8479b61fb3644/src/inline.ts#L53C9-L81

On the other hand, the plugin should recognize which is asciimath formula and LaTeX formula, but according to the [symbols list](https://asciimath.widcard.win), there's hardly any backslash followed by English letters or digital numbers. 

> Except one case: the formulas wrapped by `tex"xxxx"` will be directly put into the transformed formula. But in fact, I will directly use LaTeX ¯\\\_(ツ)\_/¯

PR is welcome here. Thanks for your suggestion!

**Comment by kwinso** [comment]
Did I get it right that I would be better to remove syntax with backticks and dollar sign (well, any custom symbol, as the settings suggest) in favor of replacing the actual math block?

**Comment by kwinso** [comment]
> there's hardly any backslash followed by English letters or digital numbers.
In ASCIIMath, it is not so many. But in LaTeX, is all over the place, so plugin can just check if it's LaTeX, then just pipe the input the the default obsidian's function for rendering math. If it's not, then plugin will use ASCIIMath.

The one additional check if should be done that there's no `tex"..." ` in the code, or it would mess up checks.

**Comment by widcardw** [comment]
It's okay, but what if the users may mess up the previous notes and new notes which contain different versions of delimiters? Is it necessary to remain the current delimiters, until they try to convert all the asciimath formulas into LaTeX?

**Comment by kwinso** [comment]
Yep, it'll mess it up. The one possible solution is to leave some kind of backwards compatibility functionality for this. 
The other approach is to remove backwards compatibility, which means that users should fix old notes by themselves.

**Comment by kwinso** [comment]
Just asking for clarification. I'm going to start working on this feature, should I keep inline `start` and `end` configurations?

**Comment by widcardw** [comment]
Yes, that's a good idea. It's all right to remove the whole `inline.ts` file. But on the other hand, we should release with a breaking change, since the previous feature will be deprecated and the users should transform all the asciimath formulas in all of their files into original LaTeX. I have created a command that can do this in one file, and this should be implemented for all the files in vault. 

As a result, we should release the following two versions:

1. Transform all the asciimath formulas into Latex (since I did not implement it in current version). (In this version, the \`\$ delimiter should be remained, while we can add the new feature)
2. Release the breaking change that deprecates the \`\$ delimiter.

If you come up with any problem, I will try to help you and solve them. We can manage the verion with **git**, so that's no problem, I will try to merge it.

**Comment by kwinso** [comment]
What about functionality with converting codeblocks with backticks and old-style inline math blocks to math with dollar-signes, but keeping it as ASCIIMath instead of converting to LaTeX.

I mean, if user has to convert all previous ASCIIMath to LaTeX, than it'll be pretty inconvenient for a user to deal with generated LaTeX instead of ASCIIMath if they had to change something.

So, basically, instead of calling `toTex(this.AM, match[4]` we just embed `match[4]`. 

The commands would be called "convert to dollar sign math". This commands will also automatically enable replaceMathBlock setting. 

I think, this should be preferred migration way, because this will keep users' ASCIIMath as it is

**Comment by widcardw** [comment]
Yeah, I've just thought about this idea. I will try to implement the command now.

**Comment by kwinso** [comment]
> Yeah, I've just thought about this idea. I will try to implement the command now.

I think you can just add a boolean parameter for this in the replace math function which is used for latex conversion, and then just check what to pass into replace strings.

**Comment by widcardw** [comment]
I've just completed the work. Please check it out. Thanks for giving so many suggestions!

**Comment by kwinso** [comment]
Haven't checked it out in the obsidian, but I've seen the code. It's great! Also, it's worth changing  migration instructions in readme about using "convert to dollar sign math" instead of "convert to LaTeX"
